### ISSUE TITLE
Does not seem to be working in VS 2015 Update 2

### ISSUE THREAD

**Issue by dparvin** [tunnelvisionlabs/InheritanceMargin#21]
I installed VS2015 Update 2 and before I installed, this extension was working, now it is not.

**Comment by 0x084E** [comment]
Same for me, I get the following error for all files:

```
Background parse (C# Inheritance Analyzer) failed in 687ms. Value cannot be null.
Parameter name: method   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, MethodInfo method)
   at Tvl.VisualStudio.InheritanceMargin.CSharp.CSharpInheritanceAnalyzer.<>c.<.cctor>b__12_2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Tvl.VisualStudio.InheritanceMargin.CSharp.CSharpInheritanceAnalyzer.ReParseImpl()
   at Tvl.VisualStudio.InheritanceMargin.CSharp.BackgroundParser.ReParse()
ByPlantDataItem.cs: Background parse (C# Inheritance Analyzer) failed in 1ms. Value cannot be null.
```

**Comment by sharwell** [comment]
This extension uses reflection to invoke methods in Roslyn that were not publicly exposed prior to Update 2. It sounds like that has changed, and the code needs to be updated accordingly. One thing to note when fixing this is the updated code will still need to work with versions of Visual Studio prior to Update 2.

**Comment by streamtree** [comment]
It's worse in Update 3 RC...it appears to be causing Visual Studio to crash.
