### ISSUE TITLE
Not working at all in VS2015 Update 3

### ISSUE THREAD

**Issue by lukaseckert** [tunnelvisionlabs/InheritanceMargin#26]
You never know how helpful a tool is until it does not work anymore... Unfortunately the extension is broken in VS2015 Update 3, this is the exception:

```
DbContextBase.cs: Background parse (C# Inheritance Analyzer) failed in 0ms. Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, MethodInfo method)
   at Tvl.VisualStudio.InheritanceMargin.CSharp.CSharpInheritanceAnalyzer.<>c.<.cctor>b__15_1()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Tvl.VisualStudio.InheritanceMargin.CSharp.CSharpInheritanceAnalyzer.ReParseImpl()
   at Tvl.VisualStudio.InheritanceMargin.CSharp.BackgroundParser.ReParse()
```
Seems like MS has changed the API again

**Comment by sharwell** [comment]
> Seems like MS has changed the API again

To be fair, we rely on reflection to call non-public functionality in Roslyn, but yes this frustrating. Thanks for reporting!
